module.exports = {
    multilingualStrings: function (lang, property) {
        const translations = {
            "en" : {
                "Submit": "Submit",
                "Delete": "Delete",
                "Run": "Run",
                "advanced search": "advanced search",
                "use current location": "use current location",
                "we looked": "we looked",
                "everywhere": "everywhere",
                "but could not find your page.": "but could not find your page.",
                "03 March 2021": "03 March 2021",
                "apply": "apply",
                "You haven't applied recently.": "You haven't applied recently.",
                "my applications": "my applications",
                "you have not saved any jobs yet": "you have not saved any jobs yet",
                "you are applying for this job:": "you are applying for this job:",
                "work from home jobs": "work from home jobs",
                "remote jobs found for you": "remote jobs found for you",
                "Page not found": "Page not found",
                "view 3 more": "view 3 more",
                "view 6 more": "view 6 more",
                "thank you for your application": "thank you for your application",
                "the application process.": "the application process.",
                "See what comes ahead in the application process": "See what comes ahead in the application process",
                "applying is easy.": "applying is easy.",
                "you get a confirmation email.": "you get a confirmation email.",
                "We'll now evaluate your application": "We'll now evaluate your application",
                "your profile matches the job": "your profile matches the job",
                "We'll contact you for some additional information.": "We'll contact you for some additional information.",
                "unsupported file type": "unsupported file type",
                "we only allow files up to 3 mb, please try again": "we only allow files up to 3 mb, please try again",
                "You have successfully updated your resume details": "You have successfully updated your resume details",
                "add files": "add files",
                "Log out": "Log out",
                "login to your account": "login to your account",
                "You removed the job from your saved jobs": "You removed the job from your saved jobs",
                "delete account": "delete account",
                "You have successfully deleted your account. A confirmation email has been sent.": "You have successfully deleted your account. A confirmation email has been sent.",
                "We do not recognize the combination of this e-mail address": "We do not recognize the combination of this e-mail address",
                "We are taking action to delete your data from our system.": "We are taking action to delete your data from our system.",
                "show job alerts": "show job alerts",
                "daily": "daily",
                "You have successfully updated your job alert.": "You have successfully updated your job alert.",
                "yes, delete": "yes, delete",
                "You have successfully deleted your job alert.": "You have successfully deleted your job alert.",
                "continue as guest": "continue as guest",
                "You'll start receiving emails": "You'll start receiving emails",
                "manage your job alerts": "manage your job alerts",
                "weekly": "weekly",
                "notification by email": "notification by email",
                "clear all": "clear all",
                "be the first to know about interesting jobs": "be the first to know about interesting jobs",
                "phone numbers": "phone numbers",
                "You can add up to two phone numbers to your profile": "You can add up to two phone numbers to your profile",
                "add phone number": "add phone number",
                "You have successfully updated your phone number": "You have successfully updated your phone number",
                "primary": "primary",
                "Mobile": "Mobile",
                "Landline": "Landline",
                "You have successfully deleted your phone number": "You have successfully deleted your phone number",
                "phone number is invalid": "phone number is invalid",
                "address": "address",
                "successfully updated your address details": "successfully updated your address details",
                "You can add up to two addresses to your profile": "You can add up to two addresses to your profile",
                "add address": "add address",
                "Primary": "Primary",
                "Bulgaria": "Bulgaria",
                "secondary": "secondary",
                "no results": "no results",
                "You have successfully updated your name details": "You have successfully updated your name details",
                "Albania": "Albania",
                "add education": "add education",
                "You have successfully updated your education details": "You have successfully updated your education details",
                "please fill in the degree name": "please fill in the degree name",
                "please fill in the degree type": "please fill in the degree type",
                "please fill in the institution / training facility / school": "please fill in the institution / training facility / school",
                "please fill in the city": "please fill in the city",
                "please fill in the country": "please fill in the country",
                "please fill in the start date": "please fill in the start date",
                "please fill in the end date": "please fill in the end date",
                "You have successfully deleted your education details": "You have successfully deleted your education details",
                "add new work experience": "add new work experience",
                "You have successfully updated your work experience details": "You have successfully updated your work experience details",
                "You have successfully deleted your work experience details": "You have successfully deleted your work experience details",
                "add certifications": "add certifications",
                "You have successfully updated your certification details": "You have successfully updated your certification details",
                "You have successfully deleted your certification details": "You have successfully deleted your certification details",
                "You have successfully updated your skills details": "You have successfully updated your skills details",
                "You have successfully deleted your skills details": "You have successfully deleted your skills details",
                "You have successfully updated your links details.": "You have successfully updated your links details.",
                "other": "other",
                "You have successfully deleted your link record": "You have successfully deleted your link record",
                "email address": "email address",
                "United Kingdom of Great Britain and Northern Ireland": "United Kingdom of Great Britain and Northern Ireland",
                "march": "march",
                "French": "French",
                "work": "work",
                "Monthly": "Monthly",
                "I prefer remote work": "I prefer remote work",
                "Work preferences have successfully been updated": "Work preferences have successfully been updated",
                "$ 2500 per month": "$ 2500 per month",
                "Value unspecified": "Value unspecified",
                "select": "select"
                },
            "de" : {
                "Submit": "Einreichen",
                "Delete": "Löschen",
                "Run": "Laufen",
                "everywhere": "nachgesehen",
                "use current location": "Standort nutzen",
                "advanced search": "Erweiterte Suche",
                "we looked": "Wir haben überall",
                "but could not find your page.": "aber die gewünsche Seite nicht gefunden",
                "03 March 2021": "03 März 2021",
                "apply": "jetzt bewerben",
                "You haven't applied recently.": "Sie haben sich in letzter Zeit nicht beworben.",
                "my applications": "Meine Bewerbungen",
                "you have not saved any jobs yet": "Sie haben sich bisher keine Stellenanzeigen gemerkt",
                "you are applying for this job:": "Bewerbung"
            },
            "nl" : {
                "we looked": "we zochten",
                "everywhere": "overal",
                "but could not find your page.": "maar konden de pagina niet vinden.",
                "Page not found": "Pagina niet gevonden",
                "03 March 2021": "03 maart 2021"
            },
            "pt" : {
                "03 March 2021": "03 março 2021"
            },
            "ar" : {
                "advanced search": "búsqueda avanzada",
                "use current location": "usar ubicación actual",
                "we looked": "buscamos por",
                "everywhere": "todas partes",
                "but could not find your page.": "pero no pudimos encontrar tu página",
                "03 March 2021": "03 marzo 2021",
            },
            "pl" : {
                "advanced search": "wyszukiwanie zaawansowane",
                "use current location": "użyj aktualnej lokalizacji",
                "we looked": "szukaliśmy",
                "everywhere": "wszędzie",
                "but could not find your page.": "ale nie mogliśmy znaleźć tej strony.",
                "03 March 2021": "03 Marzec 2021",
                "work from home jobs": "tylko praca zdalna",
                "remote jobs found for you": "zdalne oferty pracy znalezione dla Ciebie"
            },
            "cs" : {
                "advanced search": "podrobné vyhledávání",
                "use current location": "použít současnou polohu",
                "we looked": "Hledali jsme",
                "everywhere": "všude,",
                "but could not find your page.": "ale danou stránku jsme bohužel nenašli.",
                "03 March 2021": "03 Březen 2021"
            },
            "cl" : {
                "advanced search": "búsqueda avanzada",
                "use current location": "usar ubicación actual",
                "we looked": "buscamos por",
                "everywhere": "todas partes",
                "but could not find your page.": "pero no pudimos encontrar tu página",
                "03 March 2021": "03 marzo 2021",
                "work from home jobs": "solo empleos por teletrabajo",
                "remote jobs found for you": "teletrabajo trabajos para ti"
            },
            "ro" : {
                "advanced search": "căutare avansată",
                "use current location": "utilizați locația curentă",
                "we looked": "ne-am uitat",
                "everywhere": "pretutindeni",
                "but could not find your page.": "dar nu v-am putut găsi pagina.",
                "03 March 2021": "03 Martie 2021",
                "apply": "aplică"
            },
            "hu" : {
                "advanced search": "haladó keresés",
                "use current location": "használja a jelenlegi helyszínt",
                "we looked": "mindenhol",
                "everywhere": "kerestük",
                "but could not find your page.": "de nem sikerült betölteni a keresett oldalt",
                "03 March 2021": "03 március 2021",
                "apply": "jelentkezem"
            },
            "es" : {
                "advanced search": "búsqueda avanzada",
                "use current location": "usar ubicación actual",
                "we looked": "buscamos por",
                "everywhere": "todas partes",
                "but could not find your page.": "pero no pudimos encontrar tu página",
                "03 March 2021": "03 Marcha 2021"
            },
            "it" : {
                "advanced search": "ricerca avanzata",
                "use current location": "usa la posizione attuale",
                "we looked": "abbiamo guardato",
                "everywhere": "da tutte le parti",
                "but could not find your page.": "ma non sono riuscito a trovare la tua pagina.",
                "03 March 2021": "03 Marzo 2021",
                "You haven't applied recently.": "Non hai candidature recenti.",
                "my applications": "le mie candidature",
                "you have not saved any jobs yet": "non hai ancora salvato le tue offerte preferite",
                "you are applying for this job:": "ti stai candidando a questa offerta"
            },
            "de-ch" : {
                "advanced search": "fortgeschrittene Suche",
                "use current location": "Standort verwenden",
                "we looked": "wir haben nachgeschaut",
                "everywhere": "überall",
                "but could not find your page.": "aber konnten deine Seite nicht finden",
                "03 March 2021": "03 März 2021",
                "apply": "bewerben"
            },
            "pt-br" : {
                "advanced search": "pesquisa avançada",
                "use current location": "usar localização atual",
                "we looked": "nós procuramos",
                "everywhere": "em todo os lugares",
                "but could not find your page.": "mas não conseguimos encontrar o que está sendo buscado",
                "03 March 2021": "03 Marchar 2021"
            },
            "nb" : {
                "advanced search": "utvidet søk",
                "use current location": "bruk stedet du befinner deg på nå",
                "we looked": "vi har lett",
                "everywhere": "over alt",
                "but could not find your page.": "men vi kunne dessverre ikke finne siden du leter etter",
                "03 March 2021": "03 mars 2021"
            },
            "el" : {
                "advanced search": "σύνθετη αναζήτηση",
                "use current location": "χρησιμοποίησε την τρέχουσα τοποθεσία μου",
                "we looked": "ψάξαμε",
                "everywhere": "παντού",
                "but could not find your page.": "αλλά δεν μπορέσαμε να βρούμε τη σελίδα που αναζητάς.",
                "03 March 2021": "03 Μαρτίου 2021",
                "apply": "κάνε την αίτησή σου",
                "work from home jobs": "αποκλειστικά εξ αποστάσεως εργασία",
                "remote jobs found for you": "remote θέσεις εργασίας βρέθηκαν για σένα"
            },
            "fr" : {
                "advanced search": "recherche avancée",
                "use current location": "à proximité",
                "we looked": "nous avons regardé",
                "everywhere": "partout",
                "but could not find your page.": "mais nous ne trouvons pas cette page.",
                "03 March 2021": "3 mars 2021",
                "apply": "postuler",
                "You haven't applied recently.": "aucune candidature à ce jour",
                "my applications": "candidatures",
                "you have not saved any jobs yet": "pour l'instant, aucune offre sélectionnée",
                "you are applying for this job:": "vous postulez à cette offre:"
            },
            "cn" : {
                "advanced search": "高级搜索",
                "use current location": "使用当前位置",
                "we looked": "我们搜索了",
                "everywhere": "所有类目",
                "but could not find your page.": "但未查到您要找的页面",
                "03 March 2021": "03 三月 2021"
            },
            "tr" : {
                "advanced search": "gelişmiş arama",
                "use current location": "mevcut konumu kullan",
                "we looked": "her yere",
                "everywhere": "baktık",
                "but could not find your page.": "ama bulamadık",
                "03 March 2021": "03 mart 2021",
                "apply": "başvur"
            },
            "da" : {
                "advanced search": "avanceret søgning",
                "use current location": "brug nuværende lokalitet",
                "we looked": "vi har ledt",
                "everywhere": "overalt",
                "but could not find your page.": "men kunne ikke finde din side.",
                "03 March 2021": "03 marts 2021",
                "apply": "ansøg",
                "my applications": "mine ansøgninger",
                "you have not saved any jobs yet": "du har ingen gemte job endnu",
                "you are applying for this job:": "du ansøger nu dette job"
            },
            "sv" : {
                "advanced search": "avancerat sök",
                "use current location": "använd nuvarande plats",
                "we looked": "vi har sökt ",
                "everywhere": "överallt",
                "but could not find your page.": "men kan inte hitta sidan.",
                "03 March 2021": "03 Mars 2021",
                "You haven't applied recently.": "Du har inte ansökt till något jobb ännu",
                "my applications": "mina ansökningar",
                "you have not saved any jobs yet": "du har inte sparat några jobb ännu.",
                "view 3 more": "se 3 till",
                "view 6 more": "se 6 till",
                "thank you for your application": "tack för din ansökan",
                "the application process.": "ansökningsprocessen.",
                "See what comes ahead in the application process": "Se vad som händer härnäst i ansökningsprocessen",
                "applying is easy.": "att ansöka är enkelt.",
                "you get a confirmation email.": "du får ett bekräftelsemejl.",
                "We'll now evaluate your application": "Nu kommer vi snart att utvärdera hur",
                "your profile matches the job": "din profil passar för jobbet.",
                "We'll contact you for some additional information.": "Vi kommer att kontakta dig för kompletterande information.",
                "unsupported file type": "filtypen stöds ej",
                "we only allow files up to 3 mb, please try again": "vi tillåter endast filer upp till 3 mb, vänligen prova igen",
                "You have successfully updated your resume details": "Ditt CV är uppdaterat",
                "add files": "lägg till filer",
                "Log out": "Logga ut",
                "login to your account": "logga in",
                "You removed the job from your saved jobs": "Du tog bort jobbet från dina sparade jobb",
                "delete account": "radera konto",
                "You have successfully deleted your account. A confirmation email has been sent.": "Du har raderat ditt konto. Ett bekräftelsemail har skickats.",
                "We do not recognize the combination of this e-mail address": "Vi känner inte igen den här kombinationen av e-postadress och lösenord",
                "We are taking action to delete your data from our system.": "We are taking action to delete your data from our system.",
                "show job alerts": "visa jobbvarningar",
                "daily": "dagligen",
                "You have successfully updated your job alert.": "Jobbevakningen har uppdaterats.",
                "yes, delete": "ja, radera",
                "You have successfully deleted your job alert.": "Jobbevakningen är raderad.",
                "continue as guest": "fortsätt som gäst",
                "You'll start receiving emails": "u kommer att börja få e-postmeddelanden",
                "manage your job alerts": "hantera dina jobbevakningar",
                "weekly": "varje vecka",
                "notification by email": "notifieras via email",
                "clear all": "rensa allt",
                "be the first to know about interesting jobs": "be the first to know about interesting jobs",
                "phone numbers": "telefonnummer",
                "You can add up to two phone numbers to your profile": "Du kan lägga till upp till två telefonnummer",
                "add phone number": "lägg till telefonnummer",
                "You have successfully updated your phone number": "du har uppdaterat dina telefonuppgifter",
                "primary": "primär",
                "Mobile": "Mobile",
                "Landline": "Landline",
                "You have successfully deleted your phone number": "du har raderat dina telefonuppgifter",
                "phone number is invalid": "number är ogiltigt.",
                "address": "adress",
                "successfully updated your address details": "successfully updated your address details",
                "You can add up to two addresses to your profile": "Du kan lägga till upp till två adresser",
                "add address": "lägg till adress",
                "Primary": "primär",
                "Bulgaria": "Bulgarien",
                "secondary": "sekundär",
                "no results": "inget resultat",
                "You have successfully updated your name details": "Dina uppgifter är uppdaterade",
                "Albania": "Albanien",
                "add education": "lägg till utbildning",
                "You have successfully updated your education details": "Din utbildningsinformation är uppdaterad",
                "please fill in the degree name": "ange utbildningsnamn",
                "please fill in the degree type": "ange utbildningstyp",
                "please fill in the institution / training facility / school": "ange utbildningsinstans",
                "please fill in the city": "ange ort",
                "please fill in the country": "ange land",
                "please fill in the start date": "ange startdatum",
                "please fill in the end date": "ange slutdatum",
                "You have successfully deleted your education details": "Din utbildningsinformation är borttagen",
                "add new work experience": "lägg till ny arbetslivserfarenhet",
                "You have successfully updated your work experience details": "Din arbetslivserfarenhet är uppdaterad",
                "You have successfully deleted your work experience details": "Din arbetslivserfarenhet är borttagen",
                "add certifications": "lägg till certifiering",
                "You have successfully updated your certification details": "Dina certifieringar och intyg är uppdaterade",
                "You have successfully deleted your certification details": "Dina certifieringsinställningar har raderats",
                "You have successfully updated your skills details": "Din kompetens är uppdaterad",
                "You have successfully deleted your skills details": "Din kompetens är borttagen",
                "You have successfully updated your links details.": "Länkar är uppdaterade",
                "other": "annat",
                "You have successfully deleted your link record": "Länken är borttagen",
                "email address": "e-postadress",
                "United Kingdom of Great Britain and Northern Ireland": "Bulgarien",
                "march": "mars",
                "French": "Swedish",
                "work": "jobb",
                "Monthly": "Månadsvis",
                "I prefer remote work": "Jag föredrar att arbeta på distans",
                "Work preferences have successfully been updated": "Jobbpreferenser är uppdaterade",
                "$ 2500 per month": "SEK 2500 per month",
                "Value unspecified": "välj",
                "select": "välj"
            }
        }
        return translations[lang][property];
    }
};